language: julia

julia:
    - 0.6

env:
    global:
        - SSH_KEY="travis_key"
        - GIT_NAME="Frieda Rong"
        - GIT_EMAIL="adeirff@gmail.com"
        - SOURCE_DIR="target"
        - DEPLOY_BRANCH="master"

branches:
    only:
        - master

before_install:
    - openssl aes-256-cbc -K $encrypted_372990b028ab_key -iv $encrypted_372990b028ab_iv
      -in travis_key.enc -out travis_key -d

script:
    - julia --color=yes travis/get-packages.jl
    - julia --color=yes make.jl

after_success:
    - ./deploy.sh
